create table DI_MENU
(
	ID VARCHAR(255) not null
		primary key,
	ICON VARCHAR(255),
	NAME VARCHAR(255),
	NAME_EN VARCHAR(255),
	PARENT_ID VARCHAR(255),
	ROUTER VARCHAR(255),
	SEQ VARCHAR(255),
	constraint FKG964L28B4EJEQBNNW621C0156
		foreign key (PARENT_ID) references DI_MENU
)
;

create table DI_USER
(
	USER_ID INTEGER not null
		primary key,
	LOGIN_TIME TIMESTAMP,
	STATUS VARCHAR(255),
	USER_DESC VARCHAR(255),
	USER_LOGIN VARCHAR(255),
	USER_NAME VARCHAR(255),
	USER_PWD VARCHAR(255)
)
;


CREATE TABLE `FLOW` (
`ID` int(11) NOT NULL,
`PROJECT_ID` int(11) NULL,
`NAME` varchar(255) NULL,
PRIMARY KEY (`ID`)
);

CREATE TABLE `JOB` (
`ID` int(11) NOT NULL,
`PROJECT_ID` int(11) NOT NULL,
`FLOW_ID` int(11) NOT NULL,
`VERSION_ID` int(11) NOT NULL,
`NAME` varchar(255) NOT NULL,
`JOB_TYPE` varchar(255) NOT NULL,
`COMMAND` varchar(500) NOT NULL,
PRIMARY KEY (`ID`)
);

CREATE TABLE `PROJECT` (
`ID` int(11) NOT NULL,
`NAME` varchar(255) NULL,
`DESCRIPTION` varchar(4000) NULL,
PRIMARY KEY (`ID`)
);

CREATE TABLE `DEPENDENCE` (
`JOB_ID` int(11) NOT NULL,
`DEPEND_JOB_ID` int(11) NOT NULL,
PRIMARY KEY (`JOB_ID`, `DEPEND_JOB_ID`)
);

CREATE TABLE `EXEC_JOB` (
`BATCH_ID` varchar(255) NOT NULL,
`JOB_ID` int(11) NOT NULL,
`FLOW_ID` int(11) NULL,
`PROJECT_ID` int(11) NULL,
`STATUS` varchar(255) NULL,
`START_TIME` datetime NULL,
`END_TIME` datetime NULL,
`INPUT_PARAM` varchar(4000) NULL,
`OUTPUT_PARAM` varchar(4000) NULL,
`CREATE_TIME` datetime NULL,
`EXECUTOR` varchar(4000) NULL,
PRIMARY KEY (`BATCH_ID`, `JOB_ID`)
);

CREATE TABLE `VERSION` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`CREATE_TIME` datetime NULL,
PRIMARY KEY (`ID`)
);

CREATE TABLE `RELATION` (
`JOB_ID` int(11) NOT NULL,
`NEXT_JOB_ID` int(11) NOT NULL,
PRIMARY KEY (`JOB_ID`, `NEXT_JOB_ID`)
);

CREATE TABLE `JOB_BACKUP` (
`ID` int(11) NOT NULL,
`PROJECT_ID` int(11) NOT NULL,
`FLOW_ID` int(11) NOT NULL,
`VERSION_ID` int(11) NOT NULL,
`NAME` varchar(255) NOT NULL,
`JOB_TYPE` varchar(255) NOT NULL,
`COMMAND` varchar(500) NOT NULL,
`NEW_VERSION_ID` int(11) NOT NULL
);

CREATE TABLE `BATCH` (
`BATCH_ID` varchar(255) NOT NULL,
PRIMARY KEY (`BATCH_ID`)
);

CREATE TABLE `EXEC_JOB_LOG` (
`BATCH_ID` varchar(255) NOT NULL,
`JOB_ID` int(11) NULL,
`LOG` varchar(4000) NULL,
PRIMARY KEY (`BATCH_ID`)
);

CREATE TABLE `EXEC_FLOW` (
`BATCH_ID` varchar(255) NOT NULL,
`FLOW_ID` int(11) NOT NULL,
`PROJECT_ID` int(11) NULL,
`STATUS` varchar(255) NULL,
`START_TIME` datetime NULL,
`END_TIME` datetime NULL,
PRIMARY KEY (`BATCH_ID`, `FLOW_ID`)
);


ALTER TABLE `FLOW` ADD CONSTRAINT `fk_FLOW_PROJECT` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`ID`);
ALTER TABLE `DEPENDENCE` ADD CONSTRAINT `fk_DEPENDENCE` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`ID`);
ALTER TABLE `DEPENDENCE` ADD CONSTRAINT `fk_DEPENDENCE_1` FOREIGN KEY (`DEPEND_JOB_ID`) REFERENCES `JOB` (`ID`);
ALTER TABLE `EXEC_JOB` ADD CONSTRAINT `fk_JOB_INSTANCE` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`ID`);
ALTER TABLE `JOB` ADD CONSTRAINT `fk_JOB_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`ID`);
ALTER TABLE `EXEC_JOB` ADD CONSTRAINT `fk_JOB_INSTANCE_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`ID`);
ALTER TABLE `EXEC_JOB` ADD CONSTRAINT `fk_JOB_INSTANCE_2` FOREIGN KEY (`FLOW_ID`) REFERENCES `FLOW` (`ID`);
ALTER TABLE `JOB` ADD CONSTRAINT `fk_JOB_2` FOREIGN KEY (`VERSION_ID`) REFERENCES `VERSION` (`ID`);
ALTER TABLE `RELATION` ADD CONSTRAINT `fk_RELATION` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`ID`);
ALTER TABLE `RELATION` ADD CONSTRAINT `fk_RELATION_1` FOREIGN KEY (`NEXT_JOB_ID`) REFERENCES `JOB` (`ID`);
ALTER TABLE `JOB` ADD CONSTRAINT `fk_JOB` FOREIGN KEY (`FLOW_ID`) REFERENCES `FLOW` (`ID`);
ALTER TABLE `EXEC_JOB` ADD CONSTRAINT `fk_EXEC_JOB` FOREIGN KEY (`BATCH_ID`) REFERENCES `BATCH` (`BATCH_ID`);
ALTER TABLE `JOB_BACKUP` ADD CONSTRAINT `fk_JOB_BACKUP_JOB_BACKUP_1` FOREIGN KEY (`ID`) REFERENCES `JOB` (`ID`);
ALTER TABLE `EXEC_JOB_LOG` ADD CONSTRAINT `fk_EXEC_JOB_LOG_RELATION_1` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`ID`);
ALTER TABLE `EXEC_JOB_LOG` ADD CONSTRAINT `fk_EXEC_JOB_LOG_BATCH_1` FOREIGN KEY (`BATCH_ID`) REFERENCES `BATCH` (`BATCH_ID`);
ALTER TABLE `EXEC_FLOW` ADD CONSTRAINT `fk_EXEC_FLOW_FLOW_1` FOREIGN KEY (`FLOW_ID`) REFERENCES `FLOW` (`ID`);
ALTER TABLE `EXEC_FLOW` ADD CONSTRAINT `fk_EXEC_FLOW_BATCH_1` FOREIGN KEY (`BATCH_ID`) REFERENCES `BATCH` (`BATCH_ID`);

